import React, { useEffect, useState } from 'react';
import api from '../api/client';
import { EmptyRow, Feedback, PageHeader, formatDate, formatCount, getErrorMessage, getToday, usePageTitle } from '../App.jsx';

export default function Dashboard() {
  usePageTitle('Dashboard');
  const [devices, setDevices] = useState([]); const [today, setToday] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.get('/devices'), api.get('/attendance', { params: { startDate: `${getToday()}T00:00:00`, endDate: `${getToday()}T23:59:59`, pageSize: 10 } })]).then(([d, a]) => { setDevices(d.data); setToday(a.data.records || []); }).catch((e) => setError(getErrorMessage(e))); }, []);
  const online = devices.filter((d) => d.status === 'online').length;
  return <><PageHeader eyebrow="Overview" title="Good morning" description="A clear view of your workplace attendance activity today." actions={<button onClick={() => window.location.reload()}>↻ Refresh</button>} />
    {error && <Feedback error={error} />}
    <div className="stat-grid"><div className="stat-card"><span>Total devices</span><strong>{formatCount(devices.length)}</strong><small className="stat-note">Connected workspaces</small></div><div className="stat-card"><span>Devices online</span><strong>{formatCount(online)}</strong><small className="stat-note positive">● Live status</small></div><div className="stat-card"><span>Punches today</span><strong>{formatCount(today.length)}</strong><small className="stat-note">Latest activity</small></div><div className="stat-card"><span>Sync health</span><strong>{devices.length ? `${Math.round((online / devices.length) * 100)}%` : '—'}</strong><small className="stat-note">Across devices</small></div></div>
    <div className="content-grid"><section className="card"><div className="section-heading"><div><p className="eyebrow">Live network</p><h2>Device status</h2></div><span className="section-meta">{online} online</span></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>IP address</th><th>Status</th><th>Last sync</th></tr></thead><tbody>{devices.length ? devices.map((d) => <tr key={d.id}><td><strong>{d.name}</strong><small className="cell-subtitle">{d.model || 'ZKTeco device'}</small></td><td>{d.ip}</td><td><span className={`status-pill ${d.status === 'online' ? 'online' : 'offline'}`}>{d.status}</span></td><td>{formatDate(d.lastSyncAt)}</td></tr>) : <EmptyRow colSpan={4}>No devices configured yet.</EmptyRow>}</tbody></table></div></section><section className="card"><div className="section-heading"><div><p className="eyebrow">Today</p><h2>Latest punches</h2></div><span className="section-meta">{today.length} records</span></div><div className="activity-list">{today.length ? today.map((r) => <div className="activity-item" key={r.id}><span className="activity-dot" /><div><strong>{r.Employee?.name || `Unmatched user ${r.deviceUserId}`}</strong><small>{r.punchType} · {r.source}</small></div><time>{new Date(r.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>) : <Feedback empty>No punches recorded today.</Feedback>}</div></section></div></>;
}
